using System;
using System.Threading;
using System.Threading.Tasks;
using Npgsql;

namespace Ostav.Persistence
{
    public sealed class OstavPostgreSqlDatabase
    {
        public const int CurrentSchemaVersion = 1;
        private readonly string connectionString;
        private bool initialized;

        public OstavPostgreSqlDatabase(string connectionString)
        {
            if (string.IsNullOrWhiteSpace(connectionString)) throw new ArgumentException("PostgreSQL connection string is required.", nameof(connectionString));
            try { this.connectionString = new NpgsqlConnectionStringBuilder(connectionString).ConnectionString; }
            catch (Exception exception) { throw new ArgumentException("PostgreSQL connection string is invalid.", nameof(connectionString), exception); }
        }

        public async Task InitializeAsync(CancellationToken token)
        {
            await using NpgsqlConnection connection = CreateConnection();
            await connection.OpenAsync(token);
            await using NpgsqlTransaction transaction = await connection.BeginTransactionAsync(token);
            await ExecuteAsync(connection, transaction, "SELECT pg_advisory_xact_lock(hashtext('ostav_schema_migration'));", token);
            await ExecuteAsync(connection, transaction, "CREATE TABLE IF NOT EXISTS schema_info (id integer PRIMARY KEY CHECK(id=1), version integer NOT NULL);", token);
            int version;
            await using (NpgsqlCommand read = new NpgsqlCommand("SELECT version FROM schema_info WHERE id=1", connection, transaction))
            {
                object value = await read.ExecuteScalarAsync(token);
                version = value == null ? 0 : Convert.ToInt32(value);
            }
            if (version > CurrentSchemaVersion) throw new InvalidOperationException("Database schema version is newer than supported.");
            await ExecuteAsync(connection, transaction, "INSERT INTO schema_info(id,version) VALUES(1,0) ON CONFLICT(id) DO NOTHING;", token);
            await ExecuteAsync(connection, transaction, "CREATE TABLE IF NOT EXISTS state_values (namespace text NOT NULL, key text NOT NULL, value bytea NOT NULL, PRIMARY KEY(namespace,key));", token);
            await ExecuteAsync(connection, transaction, "CREATE TABLE IF NOT EXISTS idempotency_results (request_id text PRIMARY KEY, success boolean NOT NULL, code text NOT NULL, message text NOT NULL, payload_schema_id text, payload_schema_version text, payload_content_type text, payload_data text, correlation_id text, parent_request_id text, source_module_id text, requested_utc timestamptz);", token);
            await ExecuteAsync(connection, transaction, "CREATE TABLE IF NOT EXISTS audit_records (sequence bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, request_id text, correlation_id text, identity_id text, module_id text, capability_id text, operation_type text, result_code text, timestamp_utc timestamptz NOT NULL, success boolean NOT NULL);", token);
            await ExecuteAsync(connection, transaction, "CREATE TABLE IF NOT EXISTS accounts (identity_id text PRIMARY KEY, auth_subject text NOT NULL UNIQUE, display_name text NOT NULL, preferred_locale text NOT NULL, status text NOT NULL, created_utc timestamptz NOT NULL, updated_utc timestamptz NOT NULL);", token);
            await using (NpgsqlCommand update = new NpgsqlCommand("UPDATE schema_info SET version=@version WHERE id=1", connection, transaction))
            { update.Parameters.AddWithValue("version", CurrentSchemaVersion); await update.ExecuteNonQueryAsync(token); }
            await transaction.CommitAsync(token);
            initialized = true;
        }

        public async Task<NpgsqlConnection> OpenAsync(CancellationToken token)
        {
            if (!initialized) throw new InvalidOperationException("Database has not been initialized.");
            NpgsqlConnection connection = CreateConnection();
            try { await connection.OpenAsync(token); return connection; }
            catch { await connection.DisposeAsync(); throw; }
        }

        private NpgsqlConnection CreateConnection() => new NpgsqlConnection(connectionString);
        private static async Task ExecuteAsync(NpgsqlConnection connection, NpgsqlTransaction transaction, string sql, CancellationToken token)
        { await using NpgsqlCommand command = new NpgsqlCommand(sql, connection, transaction); await command.ExecuteNonQueryAsync(token); }
    }
}
